export enum CourtStatus {
  AVAILABLE = 'AVAILABLE',
  UNAVAILABLE = 'UNAVAILABLE',
  CHECKING = 'CHECKING',
  ERROR = 'ERROR',
  UNKNOWN = 'UNKNOWN',
}

export type CourtGroup = 'SUPERIOR' | 'TRF' | 'TJ' | 'TRT' | 'TRE';
export type CourtSystem = 'PJe' | 'eProc' | 'eSAJ' | 'Projudi' | 'Prop' | 'Portal';

export interface Court {
  id: string;
  acronym: string;   // tribunal code: "TRT1", "TJSP"
  system: CourtSystem;
  grau: string;      // "1G", "2G", "Portal"
  url: string;
  group: CourtGroup;
}

export interface CourtWithStatus extends Court {
  currentStatus: CourtStatus;
  lastChecked?: string;
  statusMessage?: string;
}

const c = (
  id: string, acronym: string, system: CourtSystem, grau: string,
  url: string, group: CourtGroup
): Court => ({ id, acronym, system, grau, url, group });

export const COURTS: Court[] = [
  // ==================== SUPERIORES ====================
  c('s01', 'STF',  'Prop',   '2G',     'https://sistemas.stf.jus.br/cas/login',                                                                    'SUPERIOR'),
  c('s02', 'STJ',  'Prop',   '2G',     'https://cpe.web.stj.jus.br/#/',                                                                            'SUPERIOR'),
  c('s03', 'CNJ',  'PJe',    '2G',     'https://www.cnj.jus.br/pjecnj/login.seam',                                                                 'SUPERIOR'),
  c('s04', 'TST',  'PJe',    '2G',     'https://pje.tst.jus.br/tst/login.seam',                                                                    'SUPERIOR'),
  c('s05', 'TST',  'Prop',   '2G',     'https://visualizacao-autos.tst.jus.br/visualizacaoAutos/Iniciar.pub?load=1',                                'SUPERIOR'),
  c('s06', 'TSE',  'PJe',    '2G',     'https://pje.tse.jus.br/pje/login.seam',                                                                    'SUPERIOR'),

  // ==================== TRFs ====================
  c('f01', 'TRF1',     'PJe',   '1G', 'https://pje1g.trf1.jus.br/pje/login.seam',                                                                  'TRF'),
  c('f02', 'TRF1',     'PJe',   '2G', 'https://pje2g.trf1.jus.br/pje/login.seam',                                                                  'TRF'),
  c('f03', 'TRF2',     'eProc', '2G', 'https://eproc.trf2.jus.br/eproc/externo_controlador.php?acao=selecionar_tipo_advogado_cadastrar',            'TRF'),
  c('f04', 'TRF2-JFES','eProc', '1G', 'https://eproc.jfes.jus.br/eproc/externo_controlador.php?acao=selecionar_tipo_advogado_cadastrar',            'TRF'),
  c('f05', 'TRF2-JFRJ','eProc', '1G', 'https://eproc.jfrj.jus.br/eproc/externo_controlador.php?acao=selecionar_tipo_advogado_cadastrar',            'TRF'),
  c('f06', 'TRF3',     'PJe',   '1G', 'https://pje1g.trf3.jus.br/pje/login.seam',                                                                  'TRF'),
  c('f07', 'TRF3',     'PJe',   '2G', 'https://pje2g.trf3.jus.br/pje/login.seam',                                                                  'TRF'),
  c('f08', 'TRF4',     'eProc', '2G', 'https://eproc.trf4.jus.br/eproc2trf4/externo_controlador.php?acao=selecionar_tipo_advogado_cadastrar',       'TRF'),
  c('f09', 'TRF4-JFPR','eProc', '1G', 'https://eproc.jfpr.jus.br/eprocV2/externo_controlador.php?acao=selecionar_tipo_advogado_cadastrar',          'TRF'),
  c('f10', 'TRF4-JFRS','eProc', '1G', 'https://eproc.jfrs.jus.br/eprocV2/externo_controlador.php?acao=selecionar_tipo_advogado_cadastrar',          'TRF'),
  c('f11', 'TRF4-JFSC','eProc', '1G', 'https://eproc.jfsc.jus.br/eprocV2/externo_controlador.php?acao=selecionar_tipo_advogado_cadastrar',          'TRF'),
  c('f12', 'TRF5',     'PJe',   '1G', 'https://pje1g.trf5.jus.br/pje/login.seam',                                                                  'TRF'),
  c('f13', 'TRF5',     'PJe',   '2G', 'https://pje2g.trf5.jus.br/pje/login.seam',                                                                  'TRF'),
  c('f14', 'TRF5-TRU', 'PJe',   '2G', 'https://pjett.trf5.jus.br/pje/login.seam',                                                                  'TRF'),
  c('f15', 'TRF6',     'PJe',   '1G', 'https://pje1g.trf6.jus.br/pje/login.seam',                                                                  'TRF'),
  c('f16', 'TRF6',     'PJe',   '2G', 'https://pje2g.trf6.jus.br/pje/login.seam',                                                                  'TRF'),
  c('f17', 'TRF6',     'eProc', '1G', 'https://eproc1g.trf6.jus.br/eproc/',                                                                        'TRF'),
  c('f18', 'TRF6',     'eProc', '2G', 'https://eproc2g.trf6.jus.br/eproc/',                                                                        'TRF'),

  // ==================== TRTs ====================
  c('t00', 'CSJT',  'Portal', 'Portal', 'https://jte.csjt.jus.br/home',                                 'TRT'),
  c('t01', 'TRT1',  'PJe', '1G', 'https://pje.trt1.jus.br/primeirograu/login.seam',                     'TRT'),
  c('t02', 'TRT1',  'PJe', '2G', 'https://pje.trt1.jus.br/segundograu/login.seam',                      'TRT'),
  c('t03', 'TRT2',  'PJe', '1G', 'https://pje.trt2.jus.br/primeirograu/login.seam',                     'TRT'),
  c('t04', 'TRT2',  'PJe', '2G', 'https://pje.trt2.jus.br/segundograu/login.seam',                      'TRT'),
  c('t05', 'TRT3',  'PJe', '1G', 'https://pje.trt3.jus.br/primeirograu/login.seam',                     'TRT'),
  c('t06', 'TRT3',  'PJe', '2G', 'https://pje.trt3.jus.br/segundograu/login.seam',                      'TRT'),
  c('t07', 'TRT4',  'PJe', '1G', 'https://pje.trt4.jus.br/primeirograu/login.seam',                     'TRT'),
  c('t08', 'TRT4',  'PJe', '2G', 'https://pje.trt4.jus.br/segundograu/login.seam',                      'TRT'),
  c('t09', 'TRT5',  'PJe', '1G', 'https://pje.trt5.jus.br/primeirograu/login.seam',                     'TRT'),
  c('t10', 'TRT5',  'PJe', '2G', 'https://pje.trt5.jus.br/segundograu/login.seam',                      'TRT'),
  c('t11', 'TRT6',  'PJe', '1G', 'https://pje.trt6.jus.br/primeirograu/login.seam',                     'TRT'),
  c('t12', 'TRT6',  'PJe', '2G', 'https://pje.trt6.jus.br/segundograu/login.seam',                      'TRT'),
  c('t13', 'TRT7',  'PJe', '1G', 'https://pje.trt7.jus.br/primeirograu/login.seam',                     'TRT'),
  c('t14', 'TRT7',  'PJe', '2G', 'https://pje.trt7.jus.br/segundograu/login.seam',                      'TRT'),
  c('t15', 'TRT8',  'PJe', '1G', 'https://pje.trt8.jus.br/primeirograu/login.seam',                     'TRT'),
  c('t16', 'TRT8',  'PJe', '2G', 'https://pje.trt8.jus.br/segundograu/login.seam',                      'TRT'),
  c('t17', 'TRT9',  'PJe', '1G', 'https://pje.trt9.jus.br/primeirograu/login.seam',                     'TRT'),
  c('t18', 'TRT9',  'PJe', '2G', 'https://pje.trt9.jus.br/segundograu/login.seam',                      'TRT'),
  c('t19', 'TRT10', 'PJe', '1G', 'https://pje.trt10.jus.br/primeirograu/login.seam',                    'TRT'),
  c('t20', 'TRT10', 'PJe', '2G', 'https://pje.trt10.jus.br/segundograu/login.seam',                     'TRT'),
  c('t21', 'TRT11', 'PJe', '1G', 'https://pje.trt11.jus.br/primeirograu/login.seam',                    'TRT'),
  c('t22', 'TRT11', 'PJe', '2G', 'https://pje.trt11.jus.br/segundograu/login.seam',                     'TRT'),
  c('t23', 'TRT12', 'PJe', '1G', 'https://pje.trt12.jus.br/primeirograu/login.seam',                    'TRT'),
  c('t24', 'TRT12', 'PJe', '2G', 'https://pje.trt12.jus.br/segundograu/login.seam',                     'TRT'),
  c('t25', 'TRT13', 'PJe', '1G', 'https://pje.trt13.jus.br/primeirograu/login.seam',                    'TRT'),
  c('t26', 'TRT13', 'PJe', '2G', 'https://pje.trt13.jus.br/segundograu/login.seam',                     'TRT'),
  c('t27', 'TRT14', 'PJe', '1G', 'https://pje.trt14.jus.br/primeirograu/login.seam',                    'TRT'),
  c('t28', 'TRT14', 'PJe', '2G', 'https://pje.trt14.jus.br/segundograu/login.seam',                     'TRT'),
  c('t29', 'TRT15', 'PJe', '1G', 'https://pje.trt15.jus.br/primeirograu/login.seam',                    'TRT'),
  c('t30', 'TRT15', 'PJe', '2G', 'https://pje.trt15.jus.br/segundograu/login.seam',                     'TRT'),
  c('t31', 'TRT16', 'PJe', '1G', 'https://pje.trt16.jus.br/primeirograu/login.seam',                    'TRT'),
  c('t32', 'TRT16', 'PJe', '2G', 'https://pje.trt16.jus.br/segundograu/login.seam',                     'TRT'),
  c('t33', 'TRT17', 'PJe', '1G', 'https://pje.trt17.jus.br/primeirograu/login.seam',                    'TRT'),
  c('t34', 'TRT17', 'PJe', '2G', 'https://pje.trt17.jus.br/segundograu/login.seam',                     'TRT'),
  c('t35', 'TRT18', 'PJe', '1G', 'https://pje.trt18.jus.br/primeirograu/login.seam',                    'TRT'),
  c('t36', 'TRT18', 'PJe', '2G', 'https://pje.trt18.jus.br/segundograu/login.seam',                     'TRT'),
  c('t37', 'TRT19', 'PJe', '1G', 'https://pje.trt19.jus.br/primeirograu/login.seam',                    'TRT'),
  c('t38', 'TRT19', 'PJe', '2G', 'https://pje.trt19.jus.br/segundograu/login.seam',                     'TRT'),
  c('t39', 'TRT20', 'PJe', '1G', 'https://pje.trt20.jus.br/primeirograu/login.seam',                    'TRT'),
  c('t40', 'TRT20', 'PJe', '2G', 'https://pje.trt20.jus.br/segundograu/login.seam',                     'TRT'),
  c('t41', 'TRT21', 'PJe', '1G', 'https://pje.trt21.jus.br/primeirograu/login.seam',                    'TRT'),
  c('t42', 'TRT21', 'PJe', '2G', 'https://pje.trt21.jus.br/segundograu/login.seam',                     'TRT'),
  c('t43', 'TRT22', 'PJe', '1G', 'https://pje.trt22.jus.br/primeirograu/login.seam',                    'TRT'),
  c('t44', 'TRT22', 'PJe', '2G', 'https://pje.trt22.jus.br/segundograu/login.seam',                     'TRT'),
  c('t45', 'TRT23', 'PJe', '1G', 'https://pje.trt23.jus.br/primeirograu/login.seam',                    'TRT'),
  c('t46', 'TRT23', 'PJe', '2G', 'https://pje.trt23.jus.br/segundograu/login.seam',                     'TRT'),
  c('t47', 'TRT24', 'PJe', '1G', 'https://pje.trt24.jus.br/primeirograu/login.seam',                    'TRT'),
  c('t48', 'TRT24', 'PJe', '2G', 'https://pje.trt24.jus.br/segundograu/login.seam',                     'TRT'),

  // ==================== TREs ====================
  c('e01', 'TRE-AC', 'PJe', '1G', 'https://pje1g-ac.tse.jus.br/pje/login.seam',   'TRE'),
  c('e02', 'TRE-AC', 'PJe', '2G', 'https://pje.tre-ac.jus.br/pje/login.seam',     'TRE'),
  c('e03', 'TRE-AL', 'PJe', '1G', 'https://pje1g-al.tse.jus.br/pje/login.seam',   'TRE'),
  c('e04', 'TRE-AL', 'PJe', '2G', 'https://pje.tre-al.jus.br/pje/login.seam',     'TRE'),
  c('e05', 'TRE-AM', 'PJe', '1G', 'https://pje1g-am.tse.jus.br/pje/login.seam',   'TRE'),
  c('e06', 'TRE-AM', 'PJe', '2G', 'https://pje.tre-am.jus.br/pje/login.seam',     'TRE'),
  c('e07', 'TRE-AP', 'PJe', '1G', 'https://pje1g-ap.tse.jus.br/pje/login.seam',   'TRE'),
  c('e08', 'TRE-AP', 'PJe', '2G', 'https://pje.tre-ap.jus.br/pje/login.seam',     'TRE'),
  c('e09', 'TRE-BA', 'PJe', '1G', 'https://pje1g-ba.tse.jus.br/pje/login.seam',   'TRE'),
  c('e10', 'TRE-BA', 'PJe', '2G', 'https://pje.tre-ba.jus.br/pje/login.seam',     'TRE'),
  c('e11', 'TRE-CE', 'PJe', '1G', 'https://pje1g-ce.tse.jus.br/pje/login.seam',   'TRE'),
  c('e12', 'TRE-CE', 'PJe', '2G', 'https://pje.tre-ce.jus.br/pje/login.seam',     'TRE'),
  c('e13', 'TRE-DF', 'PJe', '1G', 'https://pje1g-df.tse.jus.br/pje/login.seam',   'TRE'),
  c('e14', 'TRE-DF', 'PJe', '2G', 'https://pje.tre-df.jus.br/pje/login.seam',     'TRE'),
  c('e15', 'TRE-ES', 'PJe', '1G', 'https://pje1g-es.tse.jus.br/pje/login.seam',   'TRE'),
  c('e16', 'TRE-ES', 'PJe', '2G', 'https://pje.tre-es.jus.br/pje/login.seam',     'TRE'),
  c('e17', 'TRE-GO', 'PJe', '1G', 'https://pje1g-go.tse.jus.br/pje/login.seam',   'TRE'),
  c('e18', 'TRE-GO', 'PJe', '2G', 'https://pje.tre-go.jus.br/pje/login.seam',     'TRE'),
  c('e19', 'TRE-MA', 'PJe', '1G', 'https://pje1g-ma.tse.jus.br/pje/login.seam',   'TRE'),
  c('e20', 'TRE-MA', 'PJe', '2G', 'https://pje.tre-ma.jus.br/pje/login.seam',     'TRE'),
  c('e21', 'TRE-MG', 'PJe', '1G', 'https://pje1g-mg.tse.jus.br/pje/login.seam',   'TRE'),
  c('e22', 'TRE-MG', 'PJe', '2G', 'https://pje.tre-mg.jus.br/pje/login.seam',     'TRE'),
  c('e23', 'TRE-MS', 'PJe', '1G', 'https://pje1g-ms.tse.jus.br/pje/login.seam',   'TRE'),
  c('e24', 'TRE-MS', 'PJe', '2G', 'https://pje.tre-ms.jus.br/pje/login.seam',     'TRE'),
  c('e25', 'TRE-MT', 'PJe', '1G', 'https://pje1g-mt.tse.jus.br/pje/login.seam',   'TRE'),
  c('e26', 'TRE-MT', 'PJe', '2G', 'https://pje.tre-mt.jus.br/pje/login.seam',     'TRE'),
  c('e27', 'TRE-PA', 'PJe', '1G', 'https://pje1g-pa.tse.jus.br/pje/login.seam',   'TRE'),
  c('e28', 'TRE-PA', 'PJe', '2G', 'https://pje.tre-pa.jus.br/pje/login.seam',     'TRE'),
  c('e29', 'TRE-PB', 'PJe', '1G', 'https://pje1g-pb.tse.jus.br/pje/login.seam',   'TRE'),
  c('e30', 'TRE-PB', 'PJe', '2G', 'https://pje.tre-pb.jus.br/pje/login.seam',     'TRE'),
  c('e31', 'TRE-PE', 'PJe', '1G', 'https://pje1g-pe.tse.jus.br/pje/login.seam',   'TRE'),
  c('e32', 'TRE-PE', 'PJe', '2G', 'https://pje.tre-pe.jus.br/pje/login.seam',     'TRE'),
  c('e33', 'TRE-PI', 'PJe', '1G', 'https://pje1g-pi.tse.jus.br/pje/login.seam',   'TRE'),
  c('e34', 'TRE-PI', 'PJe', '2G', 'https://pje.tre-pi.jus.br/pje/login.seam',     'TRE'),
  c('e35', 'TRE-PR', 'PJe', '1G', 'https://pje1g-pr.tse.jus.br/pje/login.seam',   'TRE'),
  c('e36', 'TRE-PR', 'PJe', '2G', 'https://pje.tre-pr.jus.br/pje/login.seam',     'TRE'),
  c('e37', 'TRE-RJ', 'PJe', '1G', 'https://pje1g-rj.tse.jus.br/pje/login.seam',   'TRE'),
  c('e38', 'TRE-RJ', 'PJe', '2G', 'https://pje.tre-rj.jus.br/pje/login.seam',     'TRE'),
  c('e39', 'TRE-RN', 'PJe', '1G', 'https://pje1g-rn.tse.jus.br/pje/login.seam',   'TRE'),
  c('e40', 'TRE-RN', 'PJe', '2G', 'https://pje.tre-rn.jus.br/pje/login.seam',     'TRE'),
  c('e41', 'TRE-RO', 'PJe', '1G', 'https://pje1g-ro.tse.jus.br/pje/login.seam',   'TRE'),
  c('e42', 'TRE-RO', 'PJe', '2G', 'https://pje.tre-ro.jus.br/pje/login.seam',     'TRE'),
  c('e43', 'TRE-RR', 'PJe', '1G', 'https://pje1g-rr.tse.jus.br/pje/login.seam',   'TRE'),
  c('e44', 'TRE-RR', 'PJe', '2G', 'https://pje.tre-rr.jus.br/pje/login.seam',     'TRE'),
  c('e45', 'TRE-RS', 'PJe', '1G', 'https://pje1g-rs.tse.jus.br/pje/login.seam',   'TRE'),
  c('e46', 'TRE-RS', 'PJe', '2G', 'https://pje.tre-rs.jus.br/pje/login.seam',     'TRE'),
  c('e47', 'TRE-SC', 'PJe', '1G', 'https://pje1g-sc.tse.jus.br/pje/login.seam',   'TRE'),
  c('e48', 'TRE-SC', 'PJe', '2G', 'https://pje.tre-sc.jus.br/pje/login.seam',     'TRE'),
  c('e49', 'TRE-SE', 'PJe', '1G', 'https://pje1g-se.tse.jus.br/pje/login.seam',   'TRE'),
  c('e50', 'TRE-SE', 'PJe', '2G', 'https://pje.tre-se.jus.br/pje/login.seam',     'TRE'),
  c('e51', 'TRE-SP', 'PJe', '1G', 'https://pje1g-sp.tse.jus.br/pje/login.seam',   'TRE'),
  c('e52', 'TRE-SP', 'PJe', '2G', 'https://pje.tre-sp.jus.br/pje/login.seam',     'TRE'),
  c('e53', 'TRE-TO', 'PJe', '1G', 'https://pje1g-to.tse.jus.br/pje/login.seam',   'TRE'),
  c('e54', 'TRE-TO', 'PJe', '2G', 'https://pje.tre-to.jus.br/pje/login.seam',     'TRE'),

  // ==================== TJs ====================
  c('j01', 'TJAC',  'eProc',  '1G',     'https://eproc1g.tjac.jus.br/',                                                                                    'TJ'),
  c('j02', 'TJAC',  'eProc',  '2G',     'https://eproc2g.tjac.jus.br',                                                                                     'TJ'),
  c('j03', 'TJAC',  'eSAJ',   '1G',     'https://esaj.tjac.jus.br/sajcas/login?service=https%3A%2F%2Fesaj.tjac.jus.br%2Fesaj%2Fj_spring_cas_security_check','TJ'),
  c('j04', 'TJAL',  'eSAJ',   '1G',     'https://www2.tjal.jus.br/sajcas/login?service=https%3A%2F%2Fwww2.tjal.jus.br%2Fesaj%2Fj_spring_cas_security_check','TJ'),
  c('j05', 'TJAM',  'eSAJ',   '1G',     'https://consultasaj.tjam.jus.br/sajcas/login?service=https%3A%2F%2Fconsultasaj.tjam.jus.br%2Fesaj%2Fj_spring_cas_security_check','TJ'),
  c('j06', 'TJAM',  'Projudi','1G',     'https://projudi.tjam.jus.br/projudi/',                                                                             'TJ'),
  c('j07', 'TJAP',  'PJe',    '1G',     'https://pje.tjap.jus.br/1g/login.seam',                                                                           'TJ'),
  c('j08', 'TJAP',  'PJe',    '2G',     'https://pje.tjap.jus.br/2g/login.seam?loginComCertificado=false&cid=10203',                                        'TJ'),
  c('j09', 'TJBA',  'PJe',    '1G',     'https://pje.tjba.jus.br/pje/login.seam',                                                                          'TJ'),
  c('j10', 'TJBA',  'PJe',    '2G',     'https://pje2g.tjba.jus.br/pje/login.seam',                                                                        'TJ'),
  c('j11', 'TJBA',  'eProc',  '1G',     'https://eproc1g.tjba.jus.br/eproc/',                                                                              'TJ'),
  c('j12', 'TJCE',  'eSAJ',   '1G',     'https://esaj.tjce.jus.br/sajcas/login?service=https%3A%2F%2Fesaj.tjce.jus.br%2Fesaj%2Fj_spring_cas_security_check','TJ'),
  c('j13', 'TJCE',  'PJe',    '1G',     'https://pje.tjce.jus.br/pje1grau/login.seam',                                                                     'TJ'),
  c('j14', 'TJCE',  'PJe',    '2G',     'https://pje.tjce.jus.br/pje2grau/login.seam',                                                                     'TJ'),
  c('j15', 'TJDFT', 'PJe',    '1G',     'https://pje.tjdft.jus.br/pje/login.seam',                                                                         'TJ'),
  c('j16', 'TJDFT', 'PJe',    '2G',     'https://pje2i.tjdft.jus.br/pje/login.seam',                                                                       'TJ'),
  c('j17', 'TJES',  'PJe',    '2G',     'https://sistemas.tjes.jus.br/pje2g/login.seam',                                                                   'TJ'),
  c('j18', 'TJGO',  'Projudi','1G',     'https://projudi.tjgo.jus.br/#',                                                                                   'TJ'),
  c('j19', 'TJMA',  'PJe',    '1G',     'https://pje.tjma.jus.br/pje/login.seam',                                                                          'TJ'),
  c('j20', 'TJMA',  'PJe',    '2G',     'https://pje2.tjma.jus.br/pje2g/login.seam',                                                                       'TJ'),
  c('j21', 'TJMG',  'PJe',    '1G',     'https://pje.tjmg.jus.br/pje/login.seam',                                                                          'TJ'),
  c('j22', 'TJMG',  'PJe',    '2G',     'https://pjerecursal.tjmg.jus.br/pje/login.seam',                                                                  'TJ'),
  c('j23', 'TJMG',  'eProc',  '1G',     'https://eproc1g.tjmg.jus.br/eproc/',                                                                              'TJ'),
  c('j24', 'TJMG',  'eProc',  '2G',     'https://eproc2g.tjmg.jus.br/eproc/',                                                                              'TJ'),
  c('j25', 'TJMS',  'eSAJ',   '1G',     'https://esaj.tjms.jus.br/sajcas/login',                                                                           'TJ'),
  c('j26', 'TJMT',  'PJe',    '1G',     'https://pje.tjmt.jus.br/pje/login.seam',                                                                          'TJ'),
  c('j27', 'TJMT',  'PJe',    '2G',     'https://pje2.tjmt.jus.br/pje2/login.seam',                                                                        'TJ'),
  c('j28', 'TJPA',  'PJe',    '1G',     'https://pje.tjpa.jus.br/pje/login.seam',                                                                          'TJ'),
  c('j29', 'TJPA',  'PJe',    '2G',     'https://pje.tjpa.jus.br/pje-2g/login.seam',                                                                       'TJ'),
  c('j30', 'TJPB',  'PJe',    '1G',     'https://pje.tjpb.jus.br/pje/login.seam',                                                                          'TJ'),
  c('j31', 'TJPB',  'PJe',    '2G',     'https://pje.tjpb.jus.br/pje2g/login.seam',                                                                        'TJ'),
  c('j32', 'TJPE',  'PJe',    '1G',     'https://pje.tjpe.jus.br/1g/login.seam',                                                                           'TJ'),
  c('j33', 'TJPE',  'PJe',    '2G',     'https://pje.tjpe.jus.br/2g/login.seam',                                                                           'TJ'),
  c('j34', 'TJPI',  'PJe',    '1G',     'https://pje.tjpi.jus.br/1g/login.seam',                                                                           'TJ'),
  c('j35', 'TJPI',  'PJe',    '2G',     'https://pje.tjpi.jus.br/2g/login.seam',                                                                           'TJ'),
  c('j36', 'TJPR',  'Projudi','1G',     'https://projudi.tjpr.jus.br/projudi/',                                                                             'TJ'),
  c('j37', 'TJRJ',  'PJe',    '1G',     'https://tjrj.pje.jus.br/1g/login.seam',                                                                           'TJ'),
  c('j38', 'TJRJ',  'Prop',   '1G',     'https://www3.tjrj.jus.br/segweb/faces/login.jsp?indGet=true&SIGLASISTEMA=PORTALSERV',                              'TJ'),
  c('j39', 'TJRJ',  'eProc',  '1G',     'https://eproc1g.tjrj.jus.br/eproc/',                                                                              'TJ'),
  c('j40', 'TJRJ',  'eProc',  '2G',     'https://eproc2g.tjrj.jus.br/eproc/',                                                                              'TJ'),
  c('j41', 'TJRN',  'PJe',    '1G',     'https://pje1g.tjrn.jus.br/pje/login.seam',                                                                        'TJ'),
  c('j42', 'TJRN',  'PJe',    '2G',     'https://pje2g.tjrn.jus.br/pje/login.seam',                                                                        'TJ'),
  c('j43', 'TJRO',  'PJe',    '1G',     'https://pjepg.tjro.jus.br/pje',                                                                                   'TJ'),
  c('j44', 'TJRO',  'PJe',    '2G',     'https://pjesg.tjro.jus.br/pje',                                                                                   'TJ'),
  c('j45', 'TJRR',  'Projudi','1G',     'https://projudi.tjrr.jus.br/projudi/',                                                                             'TJ'),
  c('j46', 'TJRS',  'eProc',  '1G',     'https://eproc1g.tjrs.jus.br/eproc/externo_controlador.php?acao=selecionar_tipo_advogado_cadastrar',                'TJ'),
  c('j47', 'TJRS',  'eProc',  '2G',     'https://eproc2g.tjrs.jus.br/eproc/externo_controlador.php?acao=selecionar_tipo_advogado_cadastrar',                'TJ'),
  c('j48', 'TJSC',  'eProc',  '1G',     'https://eproc1g.tjsc.jus.br/eproc/externo_controlador.php?acao=selecionar_tipo_advogado_cadastrar',                'TJ'),
  c('j49', 'TJSC',  'eProc',  '2G',     'https://eproc2g.tjsc.jus.br/eproc/externo_controlador.php?acao=selecionar_tipo_advogado_cadastrar',                'TJ'),
  c('j50', 'TJSE',  'Prop',   '1G',     'https://www.tjse.jus.br/portaldoadvogado/',                                                                        'TJ'),
  c('j51', 'TJSE',  'eProc',  '1G',     'https://eproc1g.tjse.jus.br/eproc/',                                                                              'TJ'),
  c('j52', 'TJSP',  'eSAJ',   '1G',     'https://esaj.tjsp.jus.br/sajcas/login?service=https%3A%2F%2Fesaj.tjsp.jus.br%2Fesaj%2Fj_spring_cas_security_check','TJ'),
  c('j53', 'TJSP',  'eProc',  '1G',     'https://eproc1g.tjsp.jus.br/eproc/',                                                                              'TJ'),
  c('j54', 'TJSP',  'eProc',  '2G',     'https://eproc2g.tjsp.jus.br/eproc/',                                                                              'TJ'),
  c('j55', 'TJTO',  'eProc',  '1G',     'https://eproc1.tjto.jus.br/eprocV2_prod_1grau/externo_controlador.php?acao=advogado_cadastrar',                    'TJ'),
  c('j56', 'TJTO',  'eProc',  '2G',     'https://eproc2.tjto.jus.br/eprocV2_prod_2grau/',                                                                  'TJ'),
];

export const GROUP_LABELS: Record<CourtGroup, string> = {
  SUPERIOR: 'Superiores',
  TRF: 'Federais (TRFs/JFs)',
  TJ: 'Tribunais de Justiça',
  TRT: 'Tribunais do Trabalho',
  TRE: 'Tribunais Eleitorais',
};

export const SYSTEM_COLORS: Record<CourtSystem, string> = {
  PJe:     'bg-blue-100 text-blue-700',
  eProc:   'bg-emerald-100 text-emerald-700',
  eSAJ:    'bg-violet-100 text-violet-700',
  Projudi: 'bg-orange-100 text-orange-700',
  Prop:    'bg-gray-100 text-gray-600',
  Portal:  'bg-gray-100 text-gray-600',
};
