import type { CourtSystem } from './courts';

/**
 * Veredito de uma sondagem funcional.
 *
 * A razão de existir deste módulo: um tribunal pode devolver HTTP 200 e estar
 * inutilizável — página de manutenção, erro de aplicação, portal em branco.
 * Checar só o código HTTP produz falso "disponível", que é o pior erro possível
 * num sistema cuja saída vira prova de prazo.
 */
export type ProbeVerdict =
  | 'FUNCTIONAL'   // marcadores do sistema presentes: dá para operar
  | 'MAINTENANCE'  // página de manutenção/indisponibilidade declarada
  | 'BLOCKED'      // WAF ou bot-block: falha NOSSA, não do tribunal
  | 'UNEXPECTED';  // respondeu, mas sem nenhum marcador esperado

export interface ProbeEvaluation {
  verdict: ProbeVerdict;
  /** Marcador que decidiu o veredito, para entrar na evidência. */
  matched?: string;
}

/** Quanto do corpo inspecionar. Os marcadores ficam bem no começo do HTML. */
export const MAX_BODY_BYTES = 200_000;

/**
 * Bloqueio por WAF/bot-detection. Precede tudo: se nosso IP foi barrado,
 * não sabemos nada sobre o tribunal — e registrar isso como queda dele seria
 * mentira que mais tarde vira certidão falsa.
 */
const BLOCK_MARKERS: [RegExp, string][] = [
  [/the requested url was rejected/i,        'BIG-IP ASM rejeitou a requisição'],
  [/<title>\s*request rejected/i,            'Request Rejected (WAF)'],
  [/support id is/i,                         'WAF com support ID'],
  [/attention required.*cloudflare/i,        'Cloudflare bloqueou'],
  [/cf-browser-verification|__cf_chl/i,      'Cloudflare challenge'],
  [/<title>\s*just a moment/i,               'Cloudflare "Just a moment"'],
  [/access denied.*you don't have permission/i, 'Access Denied'],
  // Sem \b: o marcador aparece como "_Incapsula_Resource", e underscore é
  // caractere de palavra — a fronteira nunca existiria.
  [/incapsula|_incap_/i,                     'Imperva/Incapsula'],
  [/akamai.*reference\s*#/i,                 'Akamai bloqueou'],
  [/generated by cloudfront/i,               'CloudFront bloqueou'],
  [/the request could not be satisfied/i,    'CloudFront: request could not be satisfied'],
  [/request blocked/i,                       'Request blocked'],
  [/<title>[^<]*403 forbidden/i,             'Página 403 do servidor'],
];

/**
 * Indisponibilidade declarada pelo próprio tribunal. Muitas destas páginas
 * voltam com HTTP 200, que é exatamente o caso que o probe existe para pegar.
 */
const MAINTENANCE_MARKERS: [RegExp, string][] = [
  [/em\s+manuten[çc][ãa]o/i,                    'página de manutenção'],
  [/manuten[çc][ãa]o\s+(programada|preventiva|emergencial)/i, 'manutenção programada'],
  [/sistema\s+(est[áa]\s+)?indispon[íi]vel/i,   'sistema indisponível'],
  [/servi[çc]o\s+(est[áa]\s+)?indispon[íi]vel/i,'serviço indisponível'],
  [/temporariamente\s+(indispon[íi]vel|fora)/i, 'temporariamente indisponível'],
  [/fora\s+do\s+ar/i,                           'fora do ar'],
  [/em\s+atualiza[çc][ãa]o/i,                   'em atualização'],
  [/service\s+unavailable/i,                    'Service Unavailable'],
  [/bad\s+gateway/i,                            'Bad Gateway'],
  [/gateway\s+time-?out/i,                      'Gateway Timeout'],
  [/http\s+status\s+50\d/i,                     'HTTP 5xx na página'],
  [/erro\s+interno\s+do\s+servidor/i,           'erro interno do servidor'],
];

/**
 * Marcadores que provam que a tela de acesso do sistema carregou de fato.
 * Basta um para considerar funcional — as telas variam entre versões e
 * exigir vários geraria falso negativo.
 */
const SYSTEM_MARKERS: Record<CourtSystem, RegExp[]> = {
  PJe: [
    /j_username|j_password/i,
    /loginForm|login\.seam/i,
    /kc-form-login|kc-page-title/i,          // SSO Keycloak do PJe na nuvem
    /processo\s+judicial\s+eletr[ôo]nico/i,
    /\bpje\b/i,
  ],
  eProc: [
    /txtUsuario|pwdSenha|sbmEntrar/i,
    /externo_controlador\.php/i,
    /\beproc\b/i,
    /infra_?areaprincipal|infraBarraLocalizacao/i,
  ],
  eSAJ: [
    /sajcas|j_spring_cas_security_check/i,
    /identifica[çc][ãa]o\s+do\s+usu[áa]rio/i,
    /usuario.*senha|loginForm/i,
    /\besaj\b/i,
  ],
  Projudi: [
    /\bprojudi\b/i,
    /login.*senha/i,
    /formLogin|j_security_check/i,
  ],
  // Portais e sistemas próprios não têm assinatura comum: aceitamos qualquer
  // HTML com conteúdo, contando apenas com os marcadores negativos acima.
  Prop: [/<html|<body|<!doctype/i],
  Portal: [/<html|<body|<!doctype/i],
};

/**
 * SSO compartilhado do PDPJ. Vários eProc e PJe redirecionam para lá, e como
 * o probe não mantém cookies o Keycloak responde 400 "Cookie not found".
 * Isso não é queda: chegar à tela do SSO prova que a autenticação do tribunal
 * está de pé. Tratar como falha geraria incidente falso em cinco tribunais.
 */
const SSO_MARKERS: RegExp[] = [
  /kc-form-login|kc-page-title/i,
  /entrar\s+em\s+pdpj|realms\/pje/i,
  /\bkeycloak\b/i,
  /cookie not found/i,
];

function firstMatch(body: string, markers: [RegExp, string][]): string | undefined {
  for (const [re, label] of markers) {
    if (re.test(body)) return label;
  }
  return undefined;
}

/** Conteúdo de <title>, onde uma página de manutenção costuma se anunciar. */
function titleOf(body: string): string {
  return /<title[^>]*>([\s\S]{0,300}?)<\/title>/i.exec(body)?.[1] ?? '';
}

/** Conteúdo dos títulos visíveis da página. */
function headingsOf(body: string): string {
  const out: string[] = [];
  const re = /<h[12][^>]*>([\s\S]{0,300}?)<\/h[12]>/gi;
  let m: RegExpExecArray | null;
  while ((m = re.exec(body)) !== null) out.push(m[1]);
  return out.join(' ');
}

/** Texto visível aproximado, sem script/style/tags. */
function visibleText(body: string): string {
  return body
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

/** Acima disto a página tem conteúdo demais para ser um aviso de manutenção. */
const SHORT_PAGE_CHARS = 2000;

/**
 * Uma frase de manutenção só conta se for o assunto da página — no título, num
 * cabeçalho, ou numa página curta. Um portal inteiro que menciona "fora do ar"
 * numa notícia continua funcionando, e marcá-lo como indisponível criaria
 * incidente falso (foi exatamente o que o TJSE produziu na primeira varredura).
 */
function maintenanceIfProminent(body: string): string | undefined {
  const inTitle = firstMatch(titleOf(body), MAINTENANCE_MARKERS);
  if (inTitle) return inTitle;

  const inHeading = firstMatch(headingsOf(body), MAINTENANCE_MARKERS);
  if (inHeading) return inHeading;

  const text = visibleText(body);
  if (text.length <= SHORT_PAGE_CHARS) return firstMatch(text, MAINTENANCE_MARKERS);

  return undefined;
}

/**
 * Avalia o corpo da resposta contra a assinatura do sistema.
 *
 * A ordem importa: bloqueio antes de manutenção, manutenção antes dos
 * marcadores positivos. Uma página de manutenção do PJe ainda contém a
 * palavra "PJe", então checar o marcador positivo primeiro a daria como boa.
 */
export function evaluateBody(system: CourtSystem, body: string): ProbeEvaluation {
  const blocked = firstMatch(body, BLOCK_MARKERS);
  if (blocked) return { verdict: 'BLOCKED', matched: blocked };

  const maintenance = maintenanceIfProminent(body);
  if (maintenance) return { verdict: 'MAINTENANCE', matched: maintenance };

  const expected = SYSTEM_MARKERS[system];
  for (const re of expected) {
    if (re.test(body)) return { verdict: 'FUNCTIONAL', matched: re.source.slice(0, 40) };
  }

  // O SSO do PDPJ serve a vários sistemas: se chegamos nele, a porta existe.
  for (const re of SSO_MARKERS) {
    if (re.test(body)) return { verdict: 'FUNCTIONAL', matched: 'SSO PDPJ/Keycloak' };
  }

  return { verdict: 'UNEXPECTED' };
}
